CREATE TABLE "practice_entry" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "practice_entry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	"information" varchar(256) NOT NULL
);
--> statement-breakpoint
ALTER TABLE "practice_entry" ADD CONSTRAINT "practice_entry_createdById_practice_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."practice_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "entry_created_by_idx" ON "practice_entry" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "entry_title_idx" ON "practice_entry" USING btree ("title");--> statement-breakpoint
CREATE INDEX "entry_created_at_idx" ON "practice_entry" USING btree ("createdAt");